### ISSUE TITLE
Ibexa Upgrade 4.5.5/4.6 - Compile Error: Declaration of Ibexa\PageBuilder\PageBuilder\Timeline\Serializer\Driver\DriverFactory::createDriver(array $metadataDirs, Doctrine\Common\Annotations\Reader $annotationReader): Metadata\Driver\DriverInterface must be compatible with

### ISSUE THREAD

**Issue by jimstrike** [ibexa/experience-skeleton#7]
There is an issue upgrading Ibexa to latest 4.5.5 and 4.6 when updating with all dependencies.

`composer require ibexa/experience:4.5.5 --with-all-dependencies --no-scripts`

`Compile Error: Declaration of Ibexa\PageBuilder\PageBuilder\Timeline\Serializer\Driver\DriverFactory::createDriver(array $metadataDirs, Doctrine\Common\Annotations\Reader $annotationReader): Metadata\Driver\DriverInterface must be compatible with JMS\Serializer\Builder\DriverFactoryInterface::createDriver(array $metadataDirs, ?Doctrine\Common\Annotations\Reader $annotationReader = null): Metadata\Driver\DriverInterface`

We cannot proceed with the upgrade to 4.5.5 unless this is fixed. 

Looks like package `jms/serializer` was recently updated and added a default value to `$annotationReader` param in `DriverFactoryInterface::createDriver` method which I believe is causing the issue as Ibexa `DriverFactory` implements this interface and must be compatible with it.

Let me know if I should post this issue to `ibexa/experience` instead.

**Comment by pawankkr** [comment]
Hi. Have you resolved the issue? Which PHP version do you use?

**Comment by jimstrike** [comment]
It was resolved in a newer version of Ibexa DXP 4.6.*. Thanks.

**Comment by pawankkr** [comment]
Thank you. We are able to upgrade to the latest IBEXA 4.6.10 by following the upgrade documentation.
